// Generated by https://quicktype.io

export interface TypeProvinsi {
    id: number;
    name: string;
    code: string;
}


// Generated by https://quicktype.io

export interface TypeRooms {
    message: string;
    status_Code: number;
    data: Rooms[];
}

// Generated by https://quicktype.io

export interface Rooms {
    nomerKamar: number;
    namaKamar: string;
    ukuranKamar: string;
    hargaKamar: number;
    typeKamar: string;
    ratingKamar: number;
    diskonKamar: number;
    statusKamar: string;
    fasilitasKamar: {
        hargaFasilitas: number;
        id: number;
        name: string;
        namaFasilitas: string;
        deskripsiFasilitas: string;
        typeFasilitas: string;
    }
    images: {
        id: number;
        name: string;
        url: string;
        noKamar: number;
    }[];
}

export interface Image {
    id: number;
    name: string;
    url: string;
    noKamar: number;
}


export interface detailRoom {
    nomerKamar: number;
    namaKamar: string;
    ukuranKamar: string;
    deskripsiKamar: string;
    hargaKamar: number;
    typeKamar: string;
    ratingKamar: number;
    diskonKamar: number;
    statusKamar: string;
    fasilitasKamar: {
        id: number;
        name: string;
        namaFasilitas: string;
        deskripsiFasilitas: string;
        hargaFasilitas: number;
        typeFasilitas: string;
    }
    images: Image[]
}


// Generated by https://quicktype.io

export interface userData {
    tamuId: number;
    namaTamu: string;
    emailTamu: string;
    roleTamu: string;
    statusTamu: string;
    pekerjaan: string;
    dibuatTanggal: string;
    diupdateTanggal: string;
    jenisKelamin: string;
    provinsi: string;
    kecamatan: string;
    kelurahan: string;
    kota: string;
    nomerTelephoneTamu: string;
    umurTamu: number;
}

// Generated by https://quicktype.io

export interface Resevasi {
    status: number;
    message: string;
    data: reservasiTypes;
}

export interface reservasiTypes {
    reservationId: number;
    noKamar: number;
    noTamu: number;
    noPayment: number;
    tanggalCheckIn: any;
    tanggalCheckOut: any;
    durasiMenginap: number;
    statusReservasi: string;
    kamar: Kamar;
    tamu: Tamu;
    Payment: Payment;
}
export interface Payment {
    paymentId: number;
    noTamu: number;
    noReservasi: number;
    jumlahBayar: number;
    tanggalBayar: string;
    batasWaktuBayar: string;
    metodePembayaran: string;
    statusPembayaran: string;
}

export interface Kamar {
    nomerKamar: number;
    namaKamar: string;
    ukuranKamar: string;
    deskripsiKamar: string;
    hargaKamar: number;
    typeKamar: string;
    ratingKamar: number;
    diskonKamar: number;
    statusKamar: string;
    fasilitasId: number;
    images: Image[];
}

export interface Tamu {
    tamuId: number;
    namaTamu: string;
    emailTamu: string;
    jenisKelamin: string;
    umurTamu: number;
    nomerTelephoneTamu: string;
    provinsi: string;
    kota: string;
    kecamatan: string;
    kelurahan: string;
    password: string;
    roleTamu: string;
    statusTamu: string;
    pekerjaan: string;
    dibuatTanggal: string;
    diupdateTanggal: string;
}
