// Generated by https://quicktype.io

export interface TypeProvinsi {
    id: number;
    name: string;
    code: string;
}


// Generated by https://quicktype.io

export interface TypeRooms {
    message: string;
    status_Code: number;
    data: Rooms[];
}

// Generated by https://quicktype.io

export interface Rooms {
    nomerKamar: number;
    namaKamar: string;
    ukuranKamar: string;
    hargaKamar: number;
    typeKamar: string;
    ratingKamar: number;
    diskonKamar: number;
    statusKamar: string;
    images: {
        id: number;
        name: string;
        url: string;
        noKamar: number;
    }[];
}

export interface Image {
    id: number;
    name: string;
    url: string;
    noKamar: number;
}


export interface detailRoom {
    nomerKamar: number;
    namaKamar: string;
    ukuranKamar: string;
    deskripsiKamar: string;
    hargaKamar: number;
    typeKamar: string;
    ratingKamar: number;
    diskonKamar: number;
    statusKamar: string;
    fasiltasKamar: {
        id: number;
        name: string;
        namaFasilitas: string;
        deskripsiFasilitas: string;
        hargaFasilitas: number;
        typeFasilitas: string;
    }
    images: Image[]
}
